name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master
  create:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: cache-node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            src/node_modules
          key: ${{ matrix.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --check-files --cache-folder .ycache && rm -rf .ycache

      - name: yarn test
        run: |
          yarn build
          yarn lint
          yarn tsc
          yarn test

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [test]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          # - macos-latest
          - windows-latest
          - ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: cache-node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            src/node_modules
          key: ${{ matrix.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --check-files --cache-folder .ycache && rm -rf .ycache

      - name: publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package:publish
