name: Release

on:
  create:
    tags:
      - 'v*'
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: cache-node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            src/node_modules
          key: ${{ matrix.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn publish
